# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kite < Formula
  desc "Secure scripting runtime for operational and agentic automation with Starlark"
  homepage "https://starkite.ai"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/project-starkite/starkite/releases/download/v0.6.0/kite_0.6.0_darwin_amd64.tar.gz"
      sha256 "b8427999bc2f0ee07317133aa9e8505d325cc6f0a3897fbbbecdf8a692e7f1fd"

      define_method(:install) do
        bin.install "kite"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/project-starkite/starkite/releases/download/v0.6.0/kite_0.6.0_darwin_arm64.tar.gz"
      sha256 "7035b25334fb5dfbd204ebf6324ed416cce831a4a3c69d7533430f1cd53c446b"

      define_method(:install) do
        bin.install "kite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/project-starkite/starkite/releases/download/v0.6.0/kite_0.6.0_linux_amd64.tar.gz"
      sha256 "46e9a2b8a8c49d0c247a87cda1d9a9793568dc177572bdd241a581c02285853c"
      define_method(:install) do
        bin.install "kite"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/project-starkite/starkite/releases/download/v0.6.0/kite_0.6.0_linux_arm64.tar.gz"
      sha256 "ee206ab3aef4bf000a6f6a4ed37791f83efed9e6e432cd224844bbfe32c86a8a"
      define_method(:install) do
        bin.install "kite"
      end
    end
  end

  test do
    system "#{bin}/kite", "version"
  end
end
